BookDatabase
std::map<std::string , Book> BookDatabase::_data
Referenced by BookDatabase, find, size.
BookDatabase & BookDatabase::instance()
TO-DO (1) ////////////////////////////// Include necessary header files Hint: Include what you use, use what you include
Referenced by Bookstore::processCustomerShoppingCarts, Bookstore::reorderItems, anonymous_namespace{BookDatabaseTests.cpp}::BookDatabaseRegressionTest::tests.
Book * BookDatabase::find(const std::string &isbn)
TO-DO (3) ////////////////////////////// Implement the rest of the interface, including functions find and sizeIn function find, don't walk the collection from beginning to end (an O(n) operation), find the item with a binary search (an O(log n) operation)
References _data.
Referenced by anonymous_namespace{BookDatabaseTests.cpp}::BookDatabaseRegressionTest::tests.
std::size_t BookDatabase::size() const
References _data.
Referenced by anonymous_namespace{BookDatabaseTests.cpp}::BookDatabaseRegressionTest::tests.
BookDatabase::BookDatabase(const std::string &filename)
References _data, Book::isbn.
BookDatabase::BookDatabase(const BookDatabase &)=delete
BookDatabase& BookDatabase::operator=(const BookDatabase &)=delete