Book
std::string Book::_isbn
Referenced by isbn, operator<, operator==, operator>>.
std::string Book::_title
Referenced by operator<, operator==, operator>>, title.
std::string Book::_author
Referenced by author, operator<, operator==, operator>>.
double Book::_price
Referenced by operator<, operator==, operator>>, price.
std::ostream& operator<<(std::ostream &stream, const Book &book)
std::istream& operator>>(std::istream &stream, Book &book)
bool operator==(const Book &lhs, const Book &rhs)
bool operator<(const Book &lhs, const Book &rhs)
Book::Book(std::string_view title={}, std::string_view author={}, std::string_view isbn={}, double price=0.0)
std::string Book::isbn() const
References _isbn.
Referenced by BookDatabase::BookDatabase, anonymous_namespace{BookTests.cpp}::BookRegressionTest::construction, operator<<.
std::string Book::title() const
References _title.
Referenced by anonymous_namespace{BookTests.cpp}::BookRegressionTest::construction, operator<<, Bookstore::processCustomerShoppingCarts.
std::string Book::author() const
References _author.
Referenced by anonymous_namespace{BookTests.cpp}::BookRegressionTest::construction, operator<<.
double Book::price() const
References _price.
Referenced by anonymous_namespace{BookTests.cpp}::BookRegressionTest::comparison, anonymous_namespace{BookTests.cpp}::BookRegressionTest::construction, operator<<, Bookstore::processCustomerShoppingCarts.
void Book::isbn(std::string_view newIsbn)
References _isbn.
void Book::title(std::string_view newTitle)
References _title.
void Book::author(std::string_view newAuthor)
References _author.
void Book::price(double newPrice)
References _price.