Bookstore
using Bookstore::BooksSold = std::set<std::string >
using Bookstore::Inventory_DB = std::map<std::string , unsigned int >
using Bookstore::ShoppingCart = std::map<std::string , Book >
using Bookstore::ShoppingCarts = std::map<std::string , ShoppingCart >
constexpr unsigned int Bookstore::REORDER_THRESHOLD
Referenced by reorderItems.
constexpr unsigned int Bookstore::LOT_COUNT
Referenced by reorderItems.
Inventory_DB Bookstore::_inventoryDB
Referenced by Bookstore, inventory, processCustomerShoppingCarts, reorderItems.
Bookstore::Bookstore(const std::string &persistenyInventoryDB="BookstoreInventory.dat")
TO-DO (1) ////////////////////////////// Include necessary header files Hint: Include what you use, use what you include
References _inventoryDB.
Bookstore::Inventory_DB & Bookstore::inventory()
References _inventoryDB.
Referenced by anonymous_namespace{BookstoreTests.cpp}::BookstoreRegressionTest::BookstoreRegressionTest, main.
Bookstore::BooksSold Bookstore::processCustomerShoppingCarts(const ShoppingCarts &shoppingCarts)
References _inventoryDB, BookDatabase::instance, Book::price, Book::title.
Referenced by anonymous_namespace{BookstoreTests.cpp}::BookstoreRegressionTest::BookstoreRegressionTest, main.
void Bookstore::reorderItems(BooksSold &todaysSales)
References _inventoryDB, BookDatabase::instance, LOT_COUNT, REORDER_THRESHOLD.
Referenced by anonymous_namespace{BookstoreTests.cpp}::BookstoreRegressionTest::BookstoreRegressionTest, main.
Bookstore::ShoppingCarts Bookstore::makeShoppingCarts()
Referenced by anonymous_namespace{BookstoreTests.cpp}::BookstoreRegressionTest::BookstoreRegressionTest, main.